# Generated by Django 4.1.13 on 2024-03-17 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clothes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='clothes',
            name='type',
            field=models.CharField(default='clothes', max_length=255),
        ),
    ]
