# Generated by Django 4.1.13 on 2024-03-17 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='type',
            field=models.CharField(default='book', max_length=255),
        ),
    ]
