"""
Django settings for ecomSys_e20_02_nguyendinhtung project.

Generated by 'django-admin startproject' using Django 4.1.13.

For more information on this file, see
https://docs.djangoproject.com/en/4.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.1/ref/settings/
"""

from pathlib import Path

import book.dbRouter
import cart.dbRouter
import clothes.dbRouter
import manager.dbRouter
import mobile.dbRouter
import search.dbRouter
import user.dbRouter

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-==f$u(g)+(jz-!e8&a7$bcn6ee@x^4fp&%!ey=(a5(i4%n(p1@'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'user',
    'manager',
    'cart',
    'search',
    'book',
    'mobile',
    'clothes',
    'payment',
    'homepage',
    'crispy_forms',
    'mathfilters',
    'checkout',
    'delivery',

]

CRISPY_TEMPLATE_PACK = 'bootstrap4'


MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'ecomSys_e20_02_nguyendinhtung.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'ecomSys_e20_02_nguyendinhtung.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'ecomsys',
        'USER': 'root',
        'PASSWORD': 'Drayden123456980',
        'HOST':'localhost',
        'PORT':'3306',
    },
    'mysql': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'ecomsys',
        'USER': 'root',
        'PASSWORD': 'Drayden123456980',
        'HOST':'localhost',
        'PORT':'3306',
    },
    'mongodb':{
        'ENGINE':'djongo',
        'NAME':'ecomsys',
    }
}

DATABASE_ROUTERS = ["book.dbRouter.BookDBRouter", 
                    "cart.dbRouter.CartDBRouter", 
                    "clothes.dbRouter.ClothesDBRouter", 
                    "manager.dbRouter.ManagerDBRouter", 
                    "mobile.dbRouter.MobileDBRouter", 
                    "search.dbRouter.SearchDBRouter", 
                    "user.dbRouter.UserDBRouter"]


# Password validation
# https://docs.djangoproject.com/en/4.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.1/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/4.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
