# Generated by Django 4.1.13 on 2024-03-17 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='product_id',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='cartitem',
            name='product_price',
            field=models.IntegerField(null=True),
        ),
    ]
